api_platform:
    title: 'FindYourHome API'
    description: 'A Symfony API to simplify home buying research.'
    version: '0.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
